### ISSUE TITLE
extract FA MD

### ISSUE THREAD

**Issue by stu5** [pndni/Charge_GM_WM_Properties_Pipeline#1]
你好，我想提取DTI影像数据的FA,MD，并且进行组间比较？请问怎么提取到数值？我用dtifit转成的是FA或者MD的nii图像，所以请问怎么转成数值？
Hello, I would like to extract the DTI image data of FA,MD, and compare between groups? Excuse me how to extract the numerical value? ? I converted the NII image to FA or MD using dtifit command, so how do I convert it to a value?

**Comment by stu5** [comment]
Hello, I would like to extract the DTI image data of FA,MD, and compare between groups? Excuse me how to extract the numerical value? ? I converted the NII image to FA or MD using dtifit command, so how do I convert it to a value?

**Comment by stilley2** [comment]
Hi @stu5 . If you're running a subject through this pipeline, some FA and MD values will be in the stats files https://github.com/pndni/Charge_GM_WM_Properties_Pipeline#stats-files . Does that help? I no longer maintain this repository, so I'm tagging @amourav in case he doesn't get notifications.

**Comment by stu5** [comment]
thank you !

**Comment by stu5** [comment]
Can you give me a general idea? If I use dtifit to get FA.nii, how do I get it next, because that code is too much for me to understand, sorry

**Comment by amourav** [comment]
Thanks @stilley2. Odd that I didn't get a notification. @stu5 I will take a look.

**Comment by amourav** [comment]
@stu5 Sorry for the long reply. The stats files (stats.txt and stats_simple.txt) are in output/<subject_ID> /stats_out/stats_simple.txt. Hope I understood your question correctly.

**Comment by amourav** [comment]
closing issue now. Let me know if you have any more questions.
